'use client';
import { useState } from 'react';
import { Activity, ArrowDownLeft, ArrowUpRight, Bot, Check, CheckCheck, ChevronRight, CircleCheck, Clock3, FileText, FlaskConical, Headset, Info, LockKeyhole, MessageCircle, Pause, Pencil, Play, Plus, Radio, Save, Search, Settings2, ShieldCheck, Trash2, UsersRound, X } from 'lucide-react';
import { DEFAULT_REPLIES, metrics } from '../lib/admin';
import type { AdminView } from '../lib/admin';
import type { Action, Conversation, QuickReply, Workspace } from '../lib/types';

type Props = {
  state: Workspace; busy: boolean;
  navigate: (view: AdminView) => void;
  openChat: (chat: Conversation) => void;
  simulate: () => void;
  act: (action: Omit<Action, 'requestId'>, success?: string) => Promise<boolean>;
};
const time = (at: number) => new Date(at).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Jakarta' });

export function Overview({ state, busy, navigate, openChat, simulate, act }: Props) {
  const m = metrics(state);
  const enabled = state.botEnabled !== false;
  const latest = state.conversations.flatMap(c => c.events.map(e => ({ ...e, chat: c }))).sort((a, b) => b.at - a.at).slice(0, 5);
  return <div className="overview-page">
    <div className="overview-heading"><div><p className="eyebrow">PUSAT KENDALI REGEN</p><h2>Dashboard Overview</h2><p>Monitor percakapan, aktivitas bot, dan layanan tim dalam satu tempat.</p></div><div className="overview-actions"><button className="button" disabled={busy} onClick={() => void act({ type: enabled ? 'pause_all' : 'resume_all' }, enabled ? 'Semua balasan otomatis demo dijeda.' : 'Bot demo aktif. Percakapan admin tetap ditangani admin.')}>{enabled ? <Pause size={15} /> : <Play size={15} />}{enabled ? 'Jeda bot demo' : 'Aktifkan bot demo'}</button><button className="button primary" onClick={() => navigate('all')}><MessageCircle size={16} />Buka Live Chat</button></div></div>
    <div className="overview-stats">
      <button className="stat-card" onClick={() => navigate('channels')}><div className="stat-label">STATUS KONEKSI <Radio size={16} /></div><div className="stat-status"><span />Demo siap</div><p>WhatsApp produksi belum terhubung</p><span className="stat-link">Kelola saluran <ArrowUpRight size={13} /></span></button>
      <button className="stat-card" onClick={() => navigate('all')}><div className="stat-label">PERCAKAPAN HARI INI <MessageCircle size={16} /></div><div className="stat-value">{m.today}<span>percakapan</span></div><p>Aktivitas pesan hari ini · WIB</p><span className="stat-link">Lihat semua percakapan <ArrowUpRight size={13} /></span></button>
      <button className="stat-card" onClick={() => navigate('contacts')}><div className="stat-label">CUSTOMER / CRM <UsersRound size={16} /></div><div className="stat-value">{state.conversations.length}<span>kontak demo</span></div><p><span className="unread-inline">{m.unread}</span> pesan belum dibaca</p><span className="stat-link">Buka data pelanggan <ArrowUpRight size={13} /></span></button>
      <button className="stat-card bot-stat" onClick={() => navigate('analytics')}><div className="stat-label">BOT VS CS MANUSIA <Bot size={16} /></div><div className="stat-value">{m.botRate}<small>%</small><span>balasan bot</span></div><div className="ratio-bar"><span style={{ width: `${m.botRate}%` }} /></div><p>Bot {m.bot} <span>·</span> Admin {m.human} balasan</p></button>
    </div>
    <div className="overview-middle">
      <section className="admin-card system-card"><header><span className="card-icon"><Settings2 size={16} /></span><h3>Status ruang kerja</h3><span className="badge bot">Demo</span></header><dl><div><dt>Bot otomatis</dt><dd className={enabled ? 'green-text' : 'amber-text'}>{enabled ? 'Aktif' : 'Dijeda'}</dd></div><div><dt>Menunggu admin</dt><dd>{m.needsAdmin.length} percakapan</dd></div><div><dt>Ditangani admin</dt><dd>{m.handling} percakapan</dd></div><div><dt>Akses dashboard</dt><dd><LockKeyhole size={12} />Privat</dd></div><div><dt>Pengiriman WhatsApp</dt><dd className="muted">Tidak aktif</dd></div></dl><div className="system-footer"><ShieldCheck size={14} /><p>Mode demo terpisah dari nomor CS dan workflow produksi.</p></div></section>
      <section className="admin-card recent-card"><header><span className="card-icon warm"><Activity size={16} /></span><h3>Aktivitas terbaru</h3><button className="text-button" onClick={() => navigate('activity')}>Lihat semua <ChevronRight size={14} /></button></header><div className="recent-list">{latest.map(e => <button key={e.id} onClick={() => openChat(e.chat)}><span className={`log-label ${e.chat.mode === 'needs_admin' ? 'warning' : ''}`}>{e.chat.mode === 'needs_admin' ? 'ADMIN' : e.chat.mode === 'human' ? 'TIM' : 'BOT'}</span><div><p>{e.text}</p><small>{e.chat.name}</small></div><time>{time(e.at)}</time></button>)}</div></section>
    </div>
    <div className="overview-bottom">
      <section className="admin-card queue-card"><header><span className="card-icon warm"><Headset size={17} /></span><h3>Butuh perhatian Anda</h3><span className="queue-count">{m.needsAdmin.length}</span></header>{m.needsAdmin.length ? m.needsAdmin.slice(0, 3).map(c => <button className="queue-row" key={c.id} onClick={() => openChat(c)}><span className={`avatar ${c.color}`}>{c.initials}</span><div><strong>{c.name}</strong><p>{c.messages.at(-1)?.text}</p></div><span className="queue-action">Buka chat <ChevronRight size={13} /></span></button>) : <div className="queue-clear"><CircleCheck size={25} /><strong>Semua sudah tertangani</strong><p>Tidak ada percakapan yang menunggu admin.</p></div>}<footer><Info size={13} />Bot berhenti membalas saat percakapan diambil alih.</footer></section>
      <section className="admin-card chart-card"><header><span className="card-icon"><MessageCircle size={16} /></span><h3>Aktivitas pesan</h3><span className="chart-range">7 hari terakhir</span></header><MessageChart state={state} /><footer><span className="legend-dot" />Pesan demo masuk dan keluar <button className="text-button" onClick={() => navigate('analytics')}>Analytics <ArrowUpRight size={12} /></button></footer></section>
    </div>
    <div className="demo-start"><div><FlaskConical size={19} /><span><strong>Coba alur bot → admin</strong><small>Simulasikan pesan, ambil alih, lalu kembalikan ke bot saat siap.</small></span></div><button className="button" onClick={simulate}><Plus size={14} />Simulasikan pesan</button></div>
  </div>;
}

function MessageChart({ state }: { state: Workspace }) {
  const days = metrics(state).days; const max = Math.max(...days.map(d => d.count), 1);
  return <div className="message-chart" role="img" aria-label={days.map(d => `${d.key}: ${d.count} pesan`).join(', ')}>{days.map(d => <div className="chart-column" key={d.key}><div className="chart-bar-space"><span className="bar-total">{d.count}</span><span className={`chart-bar ${d.count ? 'has-data' : ''}`} style={{ height: `${Math.max(d.count / max * 92, 2)}px` }} /></div><small>{d.label}</small></div>)}</div>;
}

export function Analytics({ state, navigate }: Pick<Props, 'state' | 'navigate'>) {
  const m = metrics(state); const total = m.bot + m.human;
  return <div className="overview-page"><div className="overview-heading"><div><p className="eyebrow">KINERJA LAYANAN</p><h2>Analytics</h2><p>Statistik dihitung dari pesan demo tersimpan, tanpa catatan internal.</p></div><button className="button" onClick={() => navigate('all')}>Buka percakapan <ArrowUpRight size={14} /></button></div><div className="analytics-metrics">{[{ label: 'Pesan pelanggan', value: m.received, icon: ArrowDownLeft }, { label: 'Balasan bot', value: m.bot, icon: Bot }, { label: 'Balasan admin', value: m.human, icon: Headset }, { label: 'Percakapan selesai', value: m.resolved, icon: CircleCheck }].map(c => <article className="stat-card" key={c.label}><div className="stat-label">{c.label}<c.icon size={18} /></div><div className="stat-value">{c.value}</div></article>)}</div><div className="analytics-grid"><section className="admin-card chart-card"><header><h3>Pesan selama 7 hari terakhir</h3><span className="chart-range">WIB</span></header><MessageChart state={state} /><footer>Pesan masuk dan balasan yang masih tersimpan di demo.</footer></section><section className="admin-card"><header><h3>Kontribusi balasan</h3></header><div className="bot-breakdown"><div className="rate-circle" style={{ background: `conic-gradient(#176d59 0 ${m.botRate}%, #e1e8ee ${m.botRate}% 100%)` }}><span><strong>{m.botRate}%</strong><small>oleh bot</small></span></div><div><p><i className="legend-dot" />Bot <strong>{m.bot}</strong></p><p><i className="legend-dot human" />Admin <strong>{m.human}</strong></p><small>Dari {total} balasan tersimpan</small></div></div></section></div><div className="admin-card analytics-states"><header><h3>Status penanganan saat ini</h3></header>{[{ name: 'Dikelola bot', count: m.botChats, view: 'all' }, { name: 'Menunggu admin', count: m.needsAdmin.length, view: 'needs_admin' }, { name: 'Ditangani admin', count: m.handling, view: 'human' }, { name: 'Selesai', count: m.resolved, view: 'resolved' }].map(s => <button key={s.name} onClick={() => navigate(s.view as AdminView)}><span>{s.name}</span><strong>{s.count}</strong><ChevronRight size={15} /></button>)}</div></div>;
}

export function BotConfig({ state, busy, act, simulate }: Pick<Props, 'state' | 'busy' | 'act' | 'simulate'>) {
  const enabled = state.botEnabled !== false;
  return <div className="overview-page"><div className="overview-heading"><div><p className="eyebrow">OTOMATISASI & KENDALI</p><h2>AI / Bot Config</h2><p>Atur balasan otomatis demo dan pahami aturan pengambilalihan.</p></div></div><section className="admin-card bot-config-card"><header><span className="card-icon"><Bot size={18} /></span><h3>Balasan otomatis demo</h3><span className={`badge ${enabled ? 'bot' : 'needs_admin'}`}>{enabled ? 'Aktif' : 'Dijeda'}</span></header><div className="config-switch-row"><div><strong>Aktifkan bot demo</strong><p>Jika dijeda, pesan baru tetap masuk dan admin tetap dapat membalas.</p></div><button className={`switch ${enabled ? 'on' : ''}`} role="switch" aria-checked={enabled} aria-label="Aktifkan bot demo" disabled={busy} onClick={() => void act({ type: enabled ? 'pause_all' : 'resume_all' }, enabled ? 'Bot demo dijeda.' : 'Bot demo diaktifkan. Percakapan admin tetap dijeda.')}><span /></button></div><div className="config-footnote"><Info size={15} />Mengaktifkan bot global tidak mengambil kembali percakapan yang sedang ditangani admin.</div></section><div className="config-rules"><h3>Aturan supervisi</h3>{[{ title: 'Permintaan admin menghentikan bot', text: 'Pesan seperti “saya ingin bicara dengan admin” mengubah status menjadi Perlu admin.', icon: Headset }, { title: 'Admin memegang kendali sampai selesai', text: 'Setelah Ambil alih, bot tetap dijeda meskipun pelanggan mengirim pertanyaan baru.', icon: Pause }, { title: 'Aktifkan kembali secara eksplisit', text: 'Tombol Aktifkan bot di chat berlaku untuk pesan berikutnya; tidak membalas ulang pesan lama.', icon: Play }, { title: 'Jawaban contoh yang dapat diprediksi', text: 'Demo menggunakan sapaan dan jam layanan contoh. Belum terhubung ke model AI atau workflow produksi.', icon: FlaskConical }].map(r => <article className="admin-card rule-card" key={r.title}><r.icon size={21} /><div><h4>{r.title}</h4><p>{r.text}</p></div><Check size={16} /></article>)}</div><button className="button primary" onClick={simulate}><Plus size={15} />Uji dengan pesan demo</button></div>;
}

export function ReplyLibrary({ state, busy, act }: Pick<Props, 'state' | 'busy' | 'act'>) {
  const [editing, setEditing] = useState<QuickReply | null>(null);
  const [query, setQuery] = useState('');
  const replies = state.quickReplies ?? DEFAULT_REPLIES;
  return <div className="overview-page"><div className="overview-heading"><div><p className="eyebrow">PERALATAN ADMIN</p><h2>Jawaban cepat</h2><p>Simpan balasan yang sering dipakai. Pilih dari Live Chat sebelum mengirim.</p></div><button className="button primary" onClick={() => setEditing({ id: crypto.randomUUID(), title: '', text: '' })} disabled={busy || replies.length >= 20}><Plus size={15} />Tambah jawaban</button></div><label className="library-search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari judul atau isi jawaban…" aria-label="Cari jawaban cepat" /></label>{editing && <form className="admin-card reply-editor" onSubmit={async e => { e.preventDefault(); if (await act({ type: 'save_reply', replyId: editing.id, title: editing.title, text: editing.text }, 'Jawaban cepat disimpan.')) setEditing(null); }}><header><h3>{replies.some(r => r.id === editing.id) ? 'Edit jawaban' : 'Jawaban baru'}</h3><button className="icon-button" type="button" aria-label="Batalkan edit" onClick={() => setEditing(null)}><X size={17} /></button></header><label className="form-label">Judul<input required maxLength={80} value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label className="form-label">Isi jawaban<textarea required maxLength={2000} rows={4} value={editing.text} onChange={e => setEditing({ ...editing, text: e.target.value })} /></label><button type="submit" className="button primary" disabled={busy || !editing.title.trim() || !editing.text.trim()}><Save size={15} />Simpan jawaban</button></form>}<div className="reply-grid">{replies.filter(r => `${r.title} ${r.text}`.toLowerCase().includes(query.toLowerCase())).map(r => <article className="admin-card reply-card" key={r.id}><header><span className="card-icon"><FileText size={17} /></span><h3>{r.title}</h3><button className="icon-button" aria-label={`Edit ${r.title}`} onClick={() => setEditing(r)} disabled={busy}><Pencil size={15} /></button></header><p>{r.text}</p><footer><span><CheckCheck size={13} />Siap dipilih di Live Chat</span><button className="text-button" onClick={() => { if (window.confirm(`Hapus jawaban cepat “${r.title}” dari demo?`)) void act({ type: 'delete_reply', replyId: r.id }, 'Jawaban cepat dihapus.'); }} disabled={busy} aria-label={`Hapus ${r.title}`}><Trash2 size={14} /></button></footer></article>)}</div>{!replies.filter(r => `${r.title} ${r.text}`.toLowerCase().includes(query.toLowerCase())).length && <div className="empty-state"><FileText size={30} /><h3>Belum ada jawaban yang cocok</h3><p>Ubah pencarian atau tambahkan jawaban baru.</p></div>}</div>;
}
