'use client';
import { adminFetch } from './admin-client';
import { useCallback, useEffect, useState } from 'react';
import { Plus, RefreshCw, ShieldCheck, UserRound } from 'lucide-react';
import { Card, Heading, Modal, dt } from './operations-components';
import { canSupervise, roleLabel } from '../lib/admin-roles';
import type { AdminRole, AccountRole, ManagedAccount } from '../lib/admin-roles';
import { passwordValid, PASSWORD_REQUIREMENTS, MIN_PASSWORD_LENGTH, MAX_PASSWORD_LENGTH } from '../lib/admin-password-policy';

type Edit={action:'create'|'update'|'reset_password';account?:ManagedAccount};
export default function AdminAccountsPanel({role}:{role:AdminRole}){
 const [accounts,setAccounts]=useState<ManagedAccount[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[edit,setEdit]=useState<Edit|null>(null);
 const [username,setUsername]=useState(''),[displayName,setDisplayName]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[accountRole,setAccountRole]=useState<AccountRole>('admin');
 const load=useCallback(async()=>{if(!canSupervise(role))return;setLoading(true);setError('');try{const r=await adminFetch('/admin/api/admin-accounts',{cache:'no-store'});const d=await r.json() as {accounts?:ManagedAccount[];error?:string};if(!r.ok)throw Error(d.error||'Akun belum dapat dimuat.');setAccounts(d.accounts||[]);}catch(e){setError(e instanceof Error?e.message:'Akun belum dapat dimuat.');}finally{setLoading(false);}},[role]);
 useEffect(()=>{void load();},[load]);
 if(!canSupervise(role))return null;
 function open(next:Edit){setEdit(next);setUsername(next.account?.username||'');setDisplayName(next.account?.displayName||'');setAccountRole(next.account?.role||'admin');setPassword('');setConfirm('');setError('');setMessage('');}
 async function send(body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await adminFetch('/admin/api/admin-accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Akun belum tersimpan.');setEdit(null);setPassword('');setConfirm('');await load();setMessage(body.action==='create'?'Akun berhasil dibuat. Gunakan username dan password yang Anda tetapkan untuk masuk.':'Perubahan tersimpan. Sesi login lama akun tersebut telah diakhiri.');return true;}catch(e){setError(e instanceof Error?e.message:'Akun belum tersimpan.');return false;}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;if(edit.action!=='update'&&(!passwordValid(password)||password!==confirm)){setError(password!==confirm?'Konfirmasi password belum sama.':PASSWORD_REQUIREMENTS);return;}const target=edit.account?{id:edit.account.id,revision:edit.account.revision}:{};await send({action:edit.action,...target,...edit.action==='reset_password'?{password}:{username,displayName,role:accountRole,...edit.action==='create'?{password}:{}}});}
 const title=role==='owner'?'Kelola Akun':'Kelola Admin';
 return <><Heading title={title} description={role==='owner'?'Kelola akun Supervisor dan Admin untuk ruang kerja Regen.':'Buat dan kelola akun Admin yang menangani layanan pelanggan Regen.'}><button className="button" onClick={()=>void load()} disabled={loading||busy}><RefreshCw size={15}/>Muat ulang</button><button className="button primary" onClick={()=>open({action:'create'})} disabled={busy}><Plus size={16}/>Tambah {role==='owner'?'akun':'Admin'}</button></Heading>
 <div className="ops-grid two"><Card title="Supervisor"><p>Mengelola akun Admin, mengatur akses tim, dan memantau layanan.</p></Card><Card title="Admin"><p>Menangani operasional dan percakapan pelanggan. Tidak memiliki akses ke akun atau pengaturan Supervisor.</p></Card></div>
 {error&&!edit&&<p className="ops-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <Card title={role==='owner'?'Akun ruang kerja':'Akun Admin'} extra={<span className="ops-chip">{accounts.length} akun</span>}>
 {loading?<p>Memuat akun…</p>:accounts.length?<div className="ops-table-wrap"><table><thead><tr><th>Nama / username</th><th>Role</th><th>Status</th><th>Diperbarui</th><th>Tindakan</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.displayName}</strong><small style={{display:'block'}}>{a.username}</small></td><td>{a.role==='supervisor'?<ShieldCheck size={15}/>:<UserRound size={15}/>} {roleLabel(a.role)}</td><td><span className={`ops-chip ${a.enabled?'green':'amber'}`}>{a.enabled?'Aktif':'Nonaktif'}</span></td><td>{dt(a.revision)}</td><td>{a.primary?<span className="ops-muted">Akun utama · pengaturan pemilik</span>:<div className="ops-actions"><button className="button small" disabled={busy} onClick={()=>open({action:'update',account:a})}>Ubah akun</button><button className="button small" disabled={busy} onClick={()=>open({action:'reset_password',account:a})}>Reset password</button><button className={`button small ${a.enabled?'danger':''}`} disabled={busy} onClick={()=>{if(window.confirm(`${a.enabled?'Nonaktifkan':'Aktifkan'} akun ${a.username}?${a.enabled?' Sesi login akun ini akan diakhiri.':''}`))void send({action:'set_enabled',id:a.id,revision:a.revision,enabled:!a.enabled});}}>{a.enabled?'Nonaktifkan':'Aktifkan'}</button></div>}</td></tr>)}</tbody></table></div>:<div className="ops-empty compact"><UserRound size={30}/><h3>Belum ada akun Admin</h3><p>Tambahkan akun terpisah untuk setiap anggota tim.</p></div>}
 </Card>
 {edit&&<Modal title={edit.action==='create'?`Tambah ${role==='owner'?'akun':'Admin'}`:edit.action==='reset_password'?`Reset password · ${edit.account?.username}`:'Ubah akun'} onClose={()=>{if(!busy){setEdit(null);setPassword('');setConfirm('');}}}><form className="ops-form" onSubmit={save}>
 {edit.action!=='reset_password'&&<><label className="ops-field"><span>Nama</span><input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={80} required disabled={busy}/></label><label className="ops-field"><span>Username</span><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off" autoCapitalize="none" minLength={3} maxLength={64} required disabled={busy}/></label>{role==='owner'?<label className="ops-field"><span>Role</span><select value={accountRole} onChange={e=>setAccountRole(e.target.value as AccountRole)} disabled={busy}><option value="admin">Admin</option><option value="supervisor">Supervisor</option></select></label>:<p>Role: <strong>Admin</strong></p>}</>}
 {edit.action!=='update'&&<><label className="ops-field"><span>Password {edit.action==='reset_password'?'baru':''}</span><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={MIN_PASSWORD_LENGTH} maxLength={MAX_PASSWORD_LENGTH} aria-describedby="account-password-rules" required disabled={busy}/></label><label className="ops-field"><span>Ulangi password</span><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={MIN_PASSWORD_LENGTH} maxLength={MAX_PASSWORD_LENGTH} required disabled={busy}/></label><p id="account-password-rules">{PASSWORD_REQUIREMENTS}</p></>}
 {edit.action!=='create'&&<p>Perubahan ini mengakhiri sesi login lama akun tersebut.</p>}{error&&<p className="ops-error" role="alert">{error}</p>}<footer><button type="button" className="button" disabled={busy} onClick={()=>{setEdit(null);setPassword('');setConfirm('');}}>Batal</button><button className="button primary" disabled={busy}>{busy?'Menyimpan…':'Simpan akun'}</button></footer>
 </form></Modal>}
 </>;
}
