'use client';
import { adminFetch, logoutAdmin } from './admin-client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, ArrowUpRight, BookOpen, Bot, Box, CalendarDays, ChartNoAxesCombined, Check, ChevronRight, Code2, ContactRound, FileChartColumn, FileText, Globe, Headset, HeartPulse, Image, LayoutDashboard, List, LoaderCircle, LockKeyhole, LogOut, Menu, MessageCircle, MessagesSquare, Phone, Plug, Radio, RefreshCw, Search, Send, Settings2, ShieldCheck, SlidersHorizontal, Target, Truck, Users, Workflow, X } from 'lucide-react';
import { navigation } from '../lib/module-catalog';
import type { PageId } from '../lib/module-catalog';
import type { OpsEnvelope, OpsAction } from '../lib/operations';
import { REGEN_CS_PHONE, displayPhone } from '../lib/regen-phone';
import OperationsPanel from './operations-panels';
import { whatsappConnectionStatus } from '../lib/whatsapp-cs';
import type { WhatsAppConnection } from '../lib/whatsapp-cs';
import ServiceConsole from './service-console';
const icons={layout:LayoutDashboard,radio:Radio,chat:MessagesSquare,users:Users,bot:Bot,book:BookOpen,message:MessageCircle,shield:ShieldCheck,image:Image,workflow:Workflow,headset:Headset,send:Send,list:List,chart:ChartNoAxesCombined,settings:Settings2,code:Code2,heart:HeartPulse,box:Box,truck:Truck,receipt:FileText,calendar:CalendarDays,phone:Phone,globe:Globe,target:Target,contact:ContactRound,plug:Plug,report:FileChartColumn,sliders:SlidersHorizontal};
const groups={utama:'WORKSPACE',operasional:'OPERASIONAL BISNIS & LOGISTIK',integrasi:'LAYANAN & INTEGRASI'};
export default function OperationsConsole({displayName}:{displayName:string}){
 const [data,setData]=useState<OpsEnvelope|null>(null);const [page,setPage]=useState<PageId>('service');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [toast,setToast]=useState('');const [q,setQ]=useState('');const [mobile,setMobile]=useState(false);const lock=useRef(false);const search=useRef<HTMLInputElement>(null);
 const [connection,setConnection]=useState<WhatsAppConnection>(()=>whatsappConnectionStatus(undefined));
 const loadConnection=useCallback(async()=>{try{const r=await adminFetch('/admin/api/health',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const d=await r.json() as {whatsapp?:WhatsAppConnection};if(!d.whatsapp)throw Error();setConnection(d.whatsapp);}catch{setConnection(whatsappConnectionStatus(null));}},[]);
 useEffect(()=>{void loadConnection();const check=()=>{if(document.visibilityState==='visible')void loadConnection();};const timer=setInterval(check,30000);document.addEventListener('visibilitychange',check);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',check);};},[loadConnection]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await adminFetch('/admin/api/operations',{cache:'no-store'});if(r.status===401){window.location.assign('/admin/login');return;}const d=await r.json() as OpsEnvelope & {error?:string};if(!r.ok)throw new Error(d.error||'Data belum dapat dimuat.');setData(d);}catch(e){setError(e instanceof Error?e.message:'Koneksi terputus.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const wanted=location.hash.slice(1);if(wanted==='owners'||wanted==='service'||navigation.some(n=>n[0]===wanted))setPage(wanted as PageId);const onHash=()=>{const p=location.hash.slice(1);if(p==='owners'||p==='service'||navigation.some(n=>n[0]===p))setPage(p as PageId);};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[load]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);}},[toast]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setMobile(true);search.current?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const timer=setInterval(async()=>{if(lock.current||document.visibilityState!=='visible')return;try{const r=await adminFetch('/admin/api/operations',{cache:'no-store'});if(!r.ok)return;const next=await r.json() as OpsEnvelope;if(!lock.current)setData(old=>!old||next.version>old.version?next:old);}catch{}},8000);return()=>clearInterval(timer);},[]);
 function navigate(p:PageId){setPage(p);location.hash=p;setMobile(false);setQ('');setError('');}
 async function act(a:Omit<OpsAction,'requestId'>){if(!data||lock.current)return false;lock.current=true;setBusy(true);setError('');try{const r=await adminFetch('/admin/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:data.version,action:{...a,requestId:crypto.randomUUID()}})});const d=await r.json() as OpsEnvelope & {error?:string};if(d.state)setData({state:d.state,version:d.version});if(!r.ok)throw new Error(d.error||'Perubahan belum tersimpan.');setToast('Perubahan tersimpan.');return true;}catch(e){setError(e instanceof Error?e.message:'Koneksi terputus. Muat ulang sebelum mencoba kembali.');return false;}finally{lock.current=false;setBusy(false);}}
 const title=page==='service'?'Pusat CS & Transaksi':page==='owners'?'Nomor Bos & Owner':navigation.find(n=>n[0]===page)?.[1]??'Dashboard';
 return <div className={`regen-suite admin-console ${mobile?'mobile-nav-open':''}`}>
  {mobile&&<button className="ops-nav-backdrop" aria-label="Tutup navigasi" onClick={()=>setMobile(false)}/>}
  <aside className="suite-sidebar"><a href="#overview" className="suite-brand" onClick={()=>navigate('overview')}><img src="/admin-assets/regen-logo-green.png" alt="Regen Longevity Lab"/><span>ADMIN 3.0</span></a><p className="suite-caption">Pusat layanan & operasional</p><button className="suite-gateway" data-connection={connection.state} onClick={()=>navigate('gateway')}><span><small>WHATSAPP REGEN</small><strong><i/>{connection.shortLabel}</strong><em>{displayPhone(data?.state.settings.phone??REGEN_CS_PHONE)}</em></span><ChevronRight size={16}/></button><label className="suite-nav-search"><Search size={15}/><input ref={search} placeholder="Cari menu…" aria-label="Cari menu" value={q} onChange={e=>setQ(e.target.value)}/><kbd>⌘ K</kbd></label><div className="suite-nav-service"><button onClick={()=>navigate('service')} aria-current={page==='service'?'page':undefined}><MessagesSquare size={18}/>Pusat CS & Transaksi</button></div><nav aria-label="Navigasi modul">{Object.entries(groups).map(([group,label])=><div key={group} className="suite-nav-group"><h2>{label}</h2>{navigation.map(([id,text,icon,g],index)=>{if(g!==group||!text.toLowerCase().includes(q.toLowerCase()))return null;const Icon=icons[icon];return <button key={id} className={page===id?'active':''} onClick={()=>navigate(id)} aria-current={page===id?'page':undefined}><Icon size={17}/><span><small>{index+1}.</small> {text}</span>{id==='products'&&!!data?.state.records.products.filter(p=>Number(p.stock)<=Number(p.minimum)).length&&<em>{data.state.records.products.filter(p=>Number(p.stock)<=Number(p.minimum)).length}</em>}</button>;})}{group==='utama'&&(!q||'nomor bos owner'.includes(q.toLowerCase()))&&<button className={page==='owners'?'active':''} onClick={()=>navigate('owners')}><Phone size={17}/><span>Nomor Bos & Owner</span>{data?.state.records.owners.length?<em>{data.state.records.owners.length}</em>:null}</button>}</div>)}</nav><a href="https://regen-inbox.hello-wearology.chatgpt.site/admin-access" className="support">Kelola login admin</a><div className="suite-profile"><span>{displayName.slice(0,1).toUpperCase()}</span><div><strong>{displayName.split('@')[0]}</strong><small>Administrator · Privat</small></div><button type="button" onClick={()=>void logoutAdmin()} aria-label="Keluar"><LogOut size={17}/></button></div></aside>
  <main className="suite-main"><header className="suite-topbar"><div><button className="icon-button suite-menu" onClick={()=>setMobile(!mobile)} aria-label="Buka menu"><Menu size={20}/></button><strong>Regen</strong><ChevronRight size={14}/><h1>{title}</h1></div><div className="ops-actions"><span className="suite-private"><LockKeyhole size={12}/>Privat</span><button className="button" onClick={()=>{void load();void loadConnection();}} disabled={loading||busy}><RefreshCw size={14} className={loading?'spin':''}/><span>Muat ulang</span></button><a className="button suite-website" href="https://www.regenlongevitylab.com" target="_blank" rel="noreferrer">Website Regen <ArrowUpRight size={14}/></a></div></header><div className="suite-status"><span><i/>Data operasional privat</span><span title={connection.detail}>{connection.label} <button onClick={()=>navigate('gateway')}>Lihat koneksi <ChevronRight size={12}/></button></span></div>{error&&<div className="ops-error suite-error" role="alert"><span>{error}</span><button className="button small" onClick={()=>void load()} disabled={busy}>Muat ulang</button></div>}<div className="suite-content">{data?page==='service'?<ServiceConsole state={data.state} act={act} busy={busy} notice={setToast} refresh={load} navigate={p=>navigate(p as PageId)}/>:<OperationsPanel key={page} page={page} connection={connection} state={data.state} act={act} busy={busy} navigate={navigate} notice={setToast} displayName={displayName} refresh={load}/>:<div className="ops-loading"><LoaderCircle size={32} className={loading?'spin':''}/><h2>{loading?'Menyiapkan ruang kerja Regen…':'Data belum dapat dimuat'}</h2><p>{loading?'Membaca konfigurasi dan data operasional Anda.':'Gunakan Muat ulang untuk mencoba lagi.'}</p></div>}</div><footer className="suite-footer"><span>Regen Admin · 28 modul + kontak owner</span><span>WIB · Tersimpan di server{busy?' · Menyimpan…':''}</span></footer></main>{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 </div>;
}
