import { unzipSync } from 'fflate';
import { DOMParser } from '@xmldom/xmldom';
import type { Document as XmlDocument, Element as XmlElement } from '@xmldom/xmldom';
import { cleanKnowledgeText, documentText, MAX_DOCUMENT_BYTES, MAX_KNOWLEDGE_TEXT } from './knowledge';
import type { ExtractedDocument } from './knowledge';
const decode=(b:Uint8Array)=>new TextDecoder('utf-8',{fatal:true}).decode(b);
const elements=(root:XmlDocument|XmlElement,name:string)=>Array.from(root.getElementsByTagName('*')).filter(e=>e.localName===name);
function xml(bytes:Uint8Array|undefined){if(!bytes)throw new Error('Struktur dokumen tidak lengkap.');const text=decode(bytes);if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('Deklarasi XML tidak didukung.');return new DOMParser({onError:()=>{throw new Error('XML dokumen rusak.');}}).parseFromString(text,'application/xml');}
function archive(bytes:Uint8Array){let count=0,total=0;return unzipSync(bytes,{filter:f=>{count++;total+=f.originalSize;if(count>2500||total>25*1024*1024||f.originalSize>12*1024*1024)throw new Error('Dokumen terlalu besar setelah dibuka. Kurangi gambar atau jumlah data.');return /^(word\/document\.xml|xl\/workbook\.xml|xl\/_rels\/workbook\.xml\.rels|xl\/sharedStrings\.xml|xl\/styles\.xml|xl\/worksheets\/[^/]+\.xml)$/.test(f.name);}});}
function finish(d:ExtractedDocument){for(const s of d.sections)s.text=cleanKnowledgeText(s.text);d.sections=d.sections.filter(s=>s.text);const text=documentText(d);if(!text)throw new Error(d.kind==='pdf'?'PDF tidak memiliki teks yang terbaca. Lakukan OCR pada file scan, lalu unggah ulang.':'Tidak ada teks yang dapat dibaca dari dokumen.');if(text.length>MAX_KNOWLEDGE_TEXT)throw new Error('Isi melebihi 160.000 karakter. Pisahkan file menjadi beberapa dokumen.');return d;}
function word(bytes:Uint8Array,name:string):ExtractedDocument{const files=archive(bytes),doc=xml(files['word/document.xml']);const paragraphs=elements(doc,'p').map(p=>elements(p,'t').map(t=>t.textContent||'').join('')).filter(Boolean);return finish({name,kind:'docx',sections:[{title:'Isi dokumen',text:paragraphs.join('\n\n')}],warnings:['Teks utama dibaca; gambar, komentar, header/footer, dan tata letak tidak diimpor. Periksa kembali tabel.']});}
function spreadsheet(bytes:Uint8Array,name:string):ExtractedDocument{
 const files=archive(bytes),book=xml(files['xl/workbook.xml']),rels=xml(files['xl/_rels/workbook.xml.rels']);const shared=files['xl/sharedStrings.xml']?elements(xml(files['xl/sharedStrings.xml']),'si').map(si=>elements(si,'t').map(t=>t.textContent||'').join('')):[];
 const formats=files['xl/styles.xml']?elements(xml(files['xl/styles.xml']),'cellXfs')[0]:undefined;const styles=formats?elements(formats,'xf').map(e=>Number(e.getAttribute('numFmtId'))):[];const date1904=elements(book,'workbookPr')[0]?.getAttribute('date1904')==='1';
 const sheets=elements(book,'sheet');if(sheets.length>30)throw new Error('Maksimal 30 sheet per file.');const sections:ExtractedDocument['sections']=[];let cells=0,formulaCount=0,missingFormula=0,hidden=0;
 for(const sheet of sheets){if(['hidden','veryHidden'].includes(sheet.getAttribute('state')||'')){hidden++;continue;}const rel=elements(rels,'Relationship').find(r=>r.getAttribute('Id')===sheet.getAttribute('r:id'));const target=rel?.getAttribute('Target')||'';if(!target||rel?.getAttribute('TargetMode')==='External')continue;const path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');if(!/^xl\/worksheets\/[^/]+\.xml$/.test(path))throw new Error('Jalur sheet tidak valid.');const doc=xml(files[path]);const lines:string[]=[];
  for(const row of elements(doc,'row')){if(row.getAttribute('hidden')==='1')continue;const values:string[]=[];for(const c of elements(row,'c')){if(++cells>25000)throw new Error('Maksimal 25.000 sel per impor.');const reference=c.getAttribute('r')||'',type=c.getAttribute('t'),v=elements(c,'v')[0]?.textContent||'',formula=elements(c,'f')[0];if(formula){formulaCount++;if(!v){missingFormula++;continue;}}
   let value=type==='s'?shared[Number(v)]||'':type==='inlineStr'?elements(c,'t').map(t=>t.textContent||'').join(''):type==='b'?(v==='1'?'Ya':'Tidak'):v;
   const format=styles[Number(c.getAttribute('s')||0)];if(!type&&value&&Number.isFinite(Number(value))&&[14,15,16,17,18,19,20,21,22,45,46,47].includes(format)){const serial=Number(value),origin=date1904?Date.UTC(1904,0,1):Date.UTC(1899,11,30);if(serial>0&&serial<1000000)value=new Date(origin+serial*86400000).toISOString().replace('T',' ').replace(/\.000Z$/,' UTC');}
   if(value)values.push(`${reference}: ${value}`);
  }if(values.length)lines.push(values.join(' | '));}
  if(lines.length){const header=lines[0];for(let i=0;i<lines.length;i+=40)sections.push({title:`Sheet ${sheet.getAttribute('name')||'Sheet'} · baris ${i+1}–${Math.min(i+40,lines.length)}`,text:(i?`Baris awal: ${header}\n`:'')+lines.slice(i,i+40).join('\n')});}
 }
 const warnings=['Nilai dan alamat sel dibaca dari sheet terlihat. Periksa format angka, tanggal, dan susunan kolom sebelum mengaktifkan.'];if(formulaCount)warnings.push(`${formulaCount} sel formula menggunakan hasil terakhir yang tersimpan; rumus tidak dihitung ulang.`);if(missingFormula)warnings.push(`${missingFormula} formula tanpa hasil tersimpan dilewati. Buka dan simpan ulang di Excel jika nilainya diperlukan.`);if(hidden)warnings.push(`${hidden} sheet tersembunyi tidak diimpor.`);return finish({name,kind:'xlsx',sections,warnings});
}
export function extractOfficeOrText(bytes:Uint8Array,name:string):ExtractedDocument{
 if(!bytes.length||bytes.length>MAX_DOCUMENT_BYTES)throw new Error('Pilih file berukuran maksimal 8 MB.');const ext=name.split('.').at(-1)?.toLowerCase();
 if(ext==='docx')return word(bytes,name);if(ext==='xlsx')return spreadsheet(bytes,name);
 if(ext==='txt'||ext==='csv'){const text=decode(bytes).replace(/^\uFEFF/,'');if(text.includes('\x00')||/^\s*(<!doctype html|<html)/i.test(text))throw new Error('File bukan teks UTF-8 yang didukung.');return finish({name,kind:ext,sections:[{title:ext==='csv'?'Data CSV':'Isi teks',text}],warnings:ext==='csv'?['CSV diimpor sebagai teks dengan susunan kolom asli. Periksa pemisah kolom.']:[]});}
 throw new Error('Format didukung: PDF, DOCX, XLSX, CSV, dan TXT. Konversi DOC/XLS lama dahulu.');
}
export async function extractDocument(bytes:Uint8Array,name:string,onProgress:(v:string)=>void=()=>{}):Promise<ExtractedDocument>{
 if(!bytes.length||bytes.length>MAX_DOCUMENT_BYTES)throw new Error('Maksimal 8 MB per dokumen.');
 const isPdf=new TextDecoder().decode(bytes.slice(0,5))==='%PDF-';if(!isPdf){if(!/\.(docx|xlsx|csv|txt)$/i.test(name)&&bytes[0]===80&&bytes[1]===75){const files=archive(bytes);if(files['word/document.xml'])name+='.docx';else if(files['xl/workbook.xml'])name+='.xlsx';}return extractOfficeOrText(bytes,name);}
 const pdfjs=await import('pdfjs-dist-admin/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/admin-assets/pdf.worker.min.mjs?v='+pdfjs.version;
 const task=pdfjs.getDocument({data:bytes,useSystemFonts:false,disableFontFace:true,useWasm:false,cMapUrl:'/admin-assets/pdf-assets/cmaps/',cMapPacked:true,standardFontDataUrl:'/admin-assets/pdf-assets/standard_fonts/'});let timer:ReturnType<typeof setTimeout>|undefined;
 try{return await Promise.race([new Promise<never>((_,reject)=>{timer=setTimeout(()=>{void task.destroy();reject(new Error('Pembacaan PDF terlalu lama. Pecah file menjadi bagian lebih kecil.'));},90000);}), (async()=>{const doc=await task.promise;if(doc.numPages>150)throw new Error('Maksimal 150 halaman PDF per impor.');const sections:ExtractedDocument['sections']=[],empty:number[]=[];let total=0;for(let p=1;p<=doc.numPages;p++){onProgress(`Membaca halaman ${p}/${doc.numPages}…`);const page=await doc.getPage(p);const content=await page.getTextContent();const text=content.items.map(i=>'str' in i?i.str+('hasEOL' in i&&i.hasEOL?'\n':' '):'').join('');if(!text.trim())empty.push(p);sections.push({title:`Halaman ${p}`,text});total+=text.length;if(total>MAX_KNOWLEDGE_TEXT)throw new Error('PDF melebihi 160.000 karakter. Pecah file menjadi bagian lebih kecil.');page.cleanup();}return finish({name,kind:'pdf',sections,warnings:['Gambar dan tulisan di dalam gambar tidak dibaca. Periksa urutan teks dan tabel.',...(empty.length?[`Halaman tanpa teks: ${empty.join(', ')}. Gunakan OCR jika halaman tersebut memuat informasi.`]:[])]});})()]);}
 catch(e){if(e instanceof Error&&e.name==='PasswordException')throw new Error('PDF terkunci. Buka proteksi dengan izin pemilik lalu unggah ulang.');throw e;}finally{clearTimeout(timer);await task.destroy();}
}
