import type { Collection } from './operations';
export type Field={key:string;label:string;type?:'text'|'textarea'|'email'|'tel'|'number'|'datetime-local'|'checkbox'|'select'|'url';required?:boolean;options?:string[];reference?:Collection;min?:number;max?:number;hint?:string};
export type Definition={title:string;singular:string;description:string;fields:Field[];columns:string[]};
const f=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label,type,...extra});
const req={required:true};
const select=(key:string,label:string,options:string[])=>f(key,label,'select',{options});
const contact=()=>f('contactId','Pelanggan','select',{reference:'contacts',required:true});
export const definitions:Record<Collection,Definition>={
 replies:{title:'Jawaban Bot (Canned)',singular:'jawaban cepat',description:'Simpan balasan siap pakai. Salin jawaban untuk digunakan admin setelah diperiksa.',columns:['title','category','content'],fields:[f('title','Judul','text',req),f('category','Kategori'),f('content','Isi jawaban','textarea',req)]},
 contacts:{title:'Customer CRM',singular:'pelanggan',description:'Simpan profil, persetujuan komunikasi, tahap layanan, dan catatan pelanggan.',columns:['name','phone','city','stage','tags'],fields:[f('name','Nama','text',req),f('phone','Nomor WhatsApp','tel'),f('email','Email','email'),f('city','Kota'),f('address','Alamat','textarea'),select('stage','Tahap',['lead','active','follow_up','closed']),f('tags','Label (pisahkan koma)'),f('consent','Pelanggan menyetujui pesan pemasaran','checkbox'),f('notes','Catatan internal','textarea')]},
 knowledge:{title:'Knowledge Base / RAG',singular:'pengetahuan',description:'Kelola pengetahuan terverifikasi dari teks, file, dan tautan untuk AI CS.',columns:['title','category','keywords','enabled'],fields:[f('title','Judul','text',req),f('category','Kategori'),f('keywords','Kata kunci (pisahkan koma)'),f('content','Informasi terverifikasi','textarea',req),f('url','Sumber HTTPS','url'),f('enabled','Gunakan dalam pencarian','checkbox')]},
 guardrails:{title:'Forbidden / Guardrails',singular:'aturan',description:'Uji aturan kata kunci yang mengalihkan pertanyaan ke admin atau menghentikan jawaban otomatis.',columns:['name','keywords','action','enabled'],fields:[f('name','Nama aturan','text',req),f('keywords','Kata pemicu (pisahkan koma)','textarea',req),select('action','Tindakan',['handoff','block']),f('response','Jawaban pengalihan','textarea',req),f('enabled','Aktif untuk pengujian bot','checkbox')]},
 automations:{title:'Otomatisasi',singular:'otomatisasi',description:'Jalankan aturan pada stok, jadwal, dan pesanan; hasil setiap eksekusi tercatat di log.',columns:['name','trigger','action','enabled','matched'],fields:[f('name','Nama aturan','text',req),select('trigger','Saat data cocok',['low_stock','upcoming_appointment','unpaid_order']),select('action','Tindakan internal',['log','priority','tag']),f('value','Label yang ditambahkan'),f('enabled','Aturan aktif','checkbox')]},
 agents:{title:'Human CS Agent',singular:'petugas',description:'Atur daftar petugas, kapasitas dan ketersediaan tim. Akses login dashboard tetap dikelola melalui berbagi Site.',columns:['name','email','role','availability','capacity'],fields:[f('name','Nama petugas','text',req),f('email','Email','email',req),select('role','Peran operasional',['agent','supervisor','owner']),select('availability','Ketersediaan',['available','busy','offline']),f('capacity','Kapasitas chat','number',{min:1,max:100}),f('notes','Catatan shift','textarea')]},
 owners:{title:'Nomor Bos & Owner',singular:'kontak eskalasi',description:'Buku kontak internal untuk penanggung jawab dan eskalasi. Tidak ada pesan yang dikirim otomatis.',columns:['name','phone','role','enabled'],fields:[f('name','Nama','text',req),f('phone','Nomor','tel',req),select('role','Tanggung jawab',['owner','supervisor','operations']),f('enabled','Kontak aktif','checkbox'),f('notes','Petunjuk eskalasi','textarea')]},
 campaigns:{title:'Broadcast Campaign',singular:'kampanye',description:'Susun pesan dan segmentasi penerima yang sudah memberikan persetujuan; periksa pratinjau sebelum pengiriman.',columns:['name','segment','template','status'],fields:[f('name','Nama kampanye','text',req),f('segment','Label pelanggan (kosong = semua yang setuju)'),f('template','Nama template Meta'),f('message','Pesan — gunakan {{nama}} untuk nama pelanggan','textarea',req),f('schedule','Rencana waktu (WIB)','datetime-local'),f('notes','Catatan kampanye','textarea')]},
 products:{title:'Manajemen Stok',singular:'produk',description:'Pantau stok, batas minimum, harga, dan mutasi. Konfirmasi pesanan mengurangi stok secara otomatis.',columns:['sku','name','stock','minimum','price'],fields:[f('name','Nama produk','text',req),f('sku','SKU','text',req),f('category','Kategori'),f('unit','Satuan'),f('price','Harga (Rp)','number',{min:0}),f('stock','Stok awal — setelah tersimpan gunakan Mutasi','number',{min:0}),f('minimum','Stok minimum','number',{min:0}),f('notes','Catatan','textarea')]},
 orders:{title:'Pesanan & Invoicing',singular:'pesanan',description:'Buat pesanan, kelola pembayaran, dan cetak invoice. Perubahan stok mengikuti status pesanan.',columns:['number','contactId','status','total'],fields:[contact(),f('address','Alamat kirim','textarea'),f('items','Item pesanan','textarea',req),f('shipping','Ongkir (Rp)','number',{min:0}),f('discount','Diskon (Rp)','number',{min:0}),f('taxPercent','Pajak (%)','number',{min:0,max:100}),f('due','Jatuh tempo (WIB)','datetime-local'),f('notes','Catatan invoice','textarea')]},
 appointments:{title:'Jadwal Konsultasi',singular:'jadwal',description:'Susun jadwal, cegah benturan waktu petugas, dan unduh acara ke kalender.',columns:['contactId','agent','start','end','status'],fields:[contact(),f('agent','Petugas','select',{reference:'agents',required:true}),f('start','Mulai (WIB)','datetime-local',req),f('end','Selesai (WIB)','datetime-local',req),select('status','Status',['scheduled','done','cancelled']),f('location','Lokasi / tautan pertemuan'),f('notes','Catatan','textarea')]},
 shipments:{title:'Daftar Pengiriman',singular:'pengiriman',description:'Catat resi, biaya, status, dan tautan pelacakan dari kurir. Status diperbarui manual sampai penyedia terhubung.',columns:['orderId','courier','tracking','status','cost'],fields:[f('orderId','Pesanan','select',{reference:'orders',required:true}),f('courier','Kurir','text',req),f('tracking','Nomor resi','text',req),f('trackingUrl','Tautan pelacakan dari kurir','url'),select('status','Status',['packing','in_transit','delivered','returned']),f('cost','Biaya (Rp)','number',{min:0}),f('notes','Catatan','textarea')]},
 rates:{title:'Tarif Ongkir Manual',singular:'tarif',description:'Isi tarif kontrak/kurir Anda untuk menghitung estimasi. Hasil bukan tarif live dari penyedia.',columns:['destination','courier','service','base','perKg'],fields:[f('destination','Kota tujuan','text',req),f('courier','Kurir','text',req),f('service','Layanan','text',req),f('base','Biaya 1 kg pertama (Rp)','number',{min:0}),f('perKg','Tambahan per kg berikutnya (Rp)','number',{min:0}),f('eta','Estimasi tiba')]},
 calls:{title:'Pusat Panggilan & Voice',singular:'panggilan',description:'Catat panggilan, hasil, durasi, dan tindak lanjut. Gunakan tombol telepon melalui aplikasi panggilan perangkat.',columns:['contactId','direction','outcome','duration','followUp'],fields:[contact(),select('direction','Arah',['incoming','outgoing']),select('outcome','Hasil',['answered','missed','callback']),f('duration','Durasi (detik)','number',{min:0}),f('followUp','Jadwal tindak lanjut (WIB)','datetime-local'),f('notes','Ringkasan percakapan','textarea')]},
 channels:{title:'Omni-Channel & Medsos',singular:'saluran',description:'Kelola inventaris kanal, identitas akun, dan tujuan layanan. Pesan dari kanal luar memerlukan konektor.',columns:['name','provider','account','status'],fields:[f('name','Nama saluran','text',req),select('provider','Penyedia',['whatsapp','instagram','facebook','email','telegram','website']),f('account','Nomor / nama akun'),f('url','URL halaman akun','url'),f('notes','Kebutuhan koneksi','textarea')]},
 adEvents:{title:'Pelacakan Iklan & CAPI',singular:'event',description:'Catat atribusi, nilai konversi, UTM dan ID event untuk deduplikasi. Ekspor payload sebelum menghubungkan Meta CAPI.',columns:['eventId','event','contactId','value','delivery'],fields:[f('eventId','Event ID unik','text',req),select('event','Jenis event',['Lead','Contact','Purchase','Schedule']),contact(),f('value','Nilai (Rp)','number',{min:0}),f('utmSource','UTM source'),f('utmCampaign','UTM campaign'),f('sourceUrl','URL sumber'),f('consent','Persetujuan pengukuran iklan diperoleh','checkbox')]},
 integrations:{title:'Integrasi ERP',singular:'konfigurasi integrasi',description:'Siapkan pemetaan data dan ekspor JSON/CSV untuk sistem lain. Sinkronisasi API memerlukan penyedia dan kredensial server.',columns:['name','provider','direction','status'],fields:[f('name','Nama integrasi','text',req),select('provider','Jenis sistem',['erp','shipping','voice','ai','n8n','meta_capi']),select('direction','Arah data',['export','import','two_way']),f('endpoint','Alamat API HTTPS','url'),f('mapping','Pemetaan kolom (JSON)','textarea'),f('notes','Catatan konfigurasi','textarea')]}
};
export const labels:Record<string,string>={lead:'Prospek',active:'Aktif',follow_up:'Tindak lanjut',closed:'Ditutup',handoff:'Alihkan ke admin',block:'Hentikan jawaban',low_stock:'Stok ≤ minimum',upcoming_appointment:'Jadwal dalam 24 jam',unpaid_order:'Pesanan belum dibayar',log:'Catat ke log',priority:'Tandai prioritas',tag:'Tambahkan label',agent:'Petugas',supervisor:'Supervisor',owner:'Owner',available:'Tersedia',busy:'Sibuk',offline:'Tidak tersedia',draft:'Draft',awaiting_payment:'Menunggu pembayaran',ready_for_packing:'Siap dikemas',confirmed:'Dikonfirmasi',paid:'Dibayar',shipped:'Dikirim',completed:'Selesai',cancelled:'Dibatalkan',scheduled:'Terjadwal',done:'Selesai',packing:'Dikemas',in_transit:'Dalam perjalanan',delivered:'Diterima',returned:'Dikembalikan',incoming:'Masuk',outgoing:'Keluar',answered:'Terjawab',missed:'Tidak terjawab',callback:'Telepon kembali',configured:'Konfigurasi tersimpan',local:'Tercatat lokal',export:'Ekspor',import:'Impor',two_way:'Dua arah'};
export const navigation=[
 ['overview','Dashboard','layout', 'utama'],['gateway','WhatsApp Gateway','radio','utama'],['chat','Manajemen Chat','chat','utama'],['contacts','Customer CRM','users','utama'],['bot','AI / Bot Config','bot','utama'],['knowledge','Knowledge Base / RAG','book','utama'],['replies','Jawaban Bot (Canned)','message','utama'],['guardrails','Forbidden / Guardrails','shield','utama'],['media','Media Library','image','utama'],['automations','Otomatisasi','workflow','utama'],['agents','Human CS Agent','headset','utama'],['campaigns','Broadcast Campaign','send','utama'],['logs','System & Bot Logs','list','utama'],['analytics','Analytics','chart','utama'],['settings','Settings Global','settings','utama'],['api','API & Webhook','code','utama'],['health','System Health','heart','utama'],['products','Manajemen Stok','box','operasional'],['shipping','Cek Ongkir & Resi','truck','operasional'],['orders','Pesanan & Invoicing','receipt','operasional'],['appointments','Jadwal Konsultasi','calendar','operasional'],['calls','Pusat Panggilan & Voice','phone','integrasi'],['channels','Omni-Channel & Medsos','globe','integrasi'],['adEvents','Pelacakan Iklan & CAPI','target','integrasi'],['profile','Profil Pelanggan 360°','contact','integrasi'],['integrations','Integrasi ERP','plug','integrasi'],['reports','Laporan Eksekutif','report','integrasi'],['config','Pusat Konfigurasi','sliders','integrasi']
] as const;
export type PageId=typeof navigation[number][0]|'owners'|'service';
